api/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from . import views

app_name = 'api'
urlpatterns = [
    path('movie/', views.get_movie, name='movie'),
    path('intro/', views.get_intro, name='intro'),
    path('tags/', cache_page(3*60)(views.tags)),
    path('type/', cache_page(3*60)(views.get_movie_for_type))
]

movie/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'movie'
urlpatterns = [
    path('', TemplateView.as_view(template_name='movie/home.html'), name='home'),
    path('top250/', views.Top250View.as_view(), name='top250'),
    path('search/', views.search, name='search'),
    path('search_result/', views.SearchResultView.as_view(), name='search_result'),
    path('search/history/', views.HistoryView.as_view(), name='history'),
]

showmovie/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from movie_result import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('movie_result.urls')),
    path('', views.tags),
    path('user/', include('user.urls')),
    path('captcha/', include('captcha.urls')),
    path('api/', include('api.urls')),
    path('movie_result/', include('movie_result.urls')),
]

# 调试工具栏配置
if settings.DEBUG:

    import debug_toolbar

    urlpatterns.insert(0, path('__debug__/', include(debug_toolbar.urls)))

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('resister/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('confirm/', views.user_confirm, name='confirm'),
]

movie/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from user.models import User


class Top250(models.Model):
    rank = models.IntegerField(primary_key=True)
    href = models.CharField(max_length=200)
    name = models.CharField(max_length=100)
    worker = models.CharField(max_length=200, blank=True, null=True)
    category = models.CharField(max_length=100, blank=True, null=True)
    score = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'top250'
        verbose_name = 'TOP250'
        verbose_name_plural = 'TOP250'

    def __str__(self):
        return self.name


class SearchTitle(models.Model):
    title = models.CharField(max_length=30, null=False)
    create_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'title'
        verbose_name = '搜索标题'
        verbose_name_plural = '搜索标题'

    def __str__(self):
        return self.title

    @property
    def result_count(self):
        return self.searchresult_set.all().count()


class SearchResult(models.Model):
    name = models.CharField(max_length=200)
    href = models.CharField(max_length=100)
    workers = models.CharField(max_length=200)
    abstract = models.CharField(max_length=200)
    score = models.CharField(max_length=10)
    title = models.ForeignKey(SearchTitle, on_delete=models.CASCADE)

    class Meta:
        db_table = 'search_result'


class SearchRecord(models.Model):
    title = models.CharField(max_length=30, verbose_name='搜寻关键字')
    c_time = models.DateTimeField(auto_now_add=True, verbose_name='时间')
    user = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name='用户')
    result = models.BooleanField('查询是否成功')
    num = models.CharField(max_length=3, verbose_name='查询的数量')

    def __str__(self):
        return self.user.name + ':' + self.title

    class Meta:
        db_table = 'search_record'
        verbose_name = '搜索记录'
        verbose_name_plural = '搜索记录'

movie/forms.py
from django import forms

movie/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import Top250
from .search import search_movie
from .models import SearchResult, SearchTitle, SearchRecord
from django.views.generic import TemplateView, ListView, RedirectView
from django.urls import reverse
from urllib import parse
from user.models import User

# Create your views here.

#
# def home(request):
#     return render(request, 'movie/home.html')


class Top250View(ListView):
    template_name = 'movie/top250.html'
    model = Top250
    paginate_by = 25
    context_object_name = 'movies'
    ordering = 'rank'
    # def get_context_data(self, **kwargs):
    #     movies = super().get_context_data(**kwargs)
    #     # movies['movies'] = Top250.objects.all()
    #     movies['movies'] = movies['page_obj']
    #     print(movies['page_obj'], type(movies['page_obj']))
    #     print(movies['movies'], type(movies['movies']))
    #     print('movies:', movies)
    #     return movies

    def get_queryset(self):
        return Top250.objects.all()


def search(request):
    if request.method == 'POST':
        print(request.POST.dict())
        try:
            is_success = False
            num = int(request.POST['num'])
            print(num)
            if request.POST['title'] == '':
                message = '请输入搜索的关键字'
                raise ValueError
            title = request.POST['title'][0:30]
            print(title)
            if title and num:
                search_title, created = SearchTitle.objects.get_or_create(
                    title=title,
                    defaults={'title': title}
                )
                exists_result = search_title.searchresult_set.all()
                if num > exists_result.count():
                    for i in range(exists_result.count(), num, 15):
                        data_per_page = search_movie.get_content(i, title)
                        if not data_per_page:
                            break
                        movie_per_page = search_movie.detail_data(data_per_page)
                        # movies_data += movie_per_page
                        for data in movie_per_page:
                            movie_obj = SearchResult(name=data[0][0:200], href=data[1][0:100], workers=data[2][0:200],
                                                     abstract=data[3][0:200],
                                                     score=data[4],
                                                     title=search_title)
                            movie_obj.save()
                    search_result = exists_result[0:num]
                    # print(search_result)
                is_success = True
                return redirect(reverse('movie:search_result') + '?' + parse.urlencode({'title': title, 'num': num}))
        except ValueError:
            return render(request, 'movie/home.html', {'message': message, })
        finally:
            try:
                title = title
            except UnboundLocalError:
                title = '未输入有效关键字'
            num = num
            user_id = request.session['user_id']
            user = User.objects.get(id=user_id)
            print('user_id:', user_id)
            SearchRecord.objects.create(title=title, user=user, num=num, result=is_success)


class SearchResultView(ListView):
    template_name = 'movie/result.html'
    model = SearchResult
    paginate_by = 15
    context_object_name = 'movies'
    http_method_names = 'get'

    def get_queryset(self):
        keys = self.request.GET.dict()
        title = keys['title']
        search_title = SearchTitle.objects.get(title=title)
        num = int(keys['num'])
        return SearchResult.objects.filter(title=search_title)[0:num]

    def get_context_data(self, *, object_list=None, **kwargs):
        result = super().get_context_data(**kwargs)
        result['params'] = self.request.GET.dict()
        # print(result)
        return result
    # def get_context_data(self, **kwargs):
    #     movies = super().get_context_data(**kwargs).filter
    # #     # movies['movies'] = Top250.objects.all()
    # #     movies['movies'] = movies['page_obj']
    # #     print(movies['page_obj'], type(movies['page_obj']))
    # #     print(movies['movies'], type(movies['movies']))
    #     print('movies:', movies)
    #     return movies
# class SearchView(ListView):
#
#     def post(self):
#         title = request.GET.get('title')
#         print('title:', title, type(title))
#         page_num = int(request.GET.get('page_num'))


class HistoryView(ListView):
    template_name = 'movie/search_history.html'
    model = SearchRecord
    context_object_name = 'historys'
    ordering = '-c_time'

    def get_queryset(self):
        user_id = self.request.session['user_id']
        user = User.objects.get(id=user_id)
        print()
        return SearchRecord.objects.filter(user=user)

movie/templates/movie/home.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'movie/css/home.css' %}">
<div class="">
    <div class="float_clear">
    <div class="user">
    {% if request.session.user_id %}
    <span>Hi,&nbsp;{{ request.session.user_name }}</span>&nbsp;&nbsp;
        {% if  not request.session.has_confirm %}
            <span>您的邮箱未确认,请及时去注册邮箱确认</span>
<!--        <a href="{% url 'user:confirm' %}">去确定</a>-->
        {% endif %}
        <p><a href="{% url 'user:logout' %}">注销</a></p>
    {% else %}
    <a href="{% url 'user:login' %}">登录</a>&nbsp;&nbsp;
    <a href="{% url 'user:register' %}">注册</a>
        {% endif %}
</div>
</div>
    <h1><a href="{% url 'movie:top250' %}">豆瓣电影TOP250</a></h1>
    <p>{{ message }}</p>
    <form action="/movie_result/search_subjects/"  method="get">
        <div>输入要搜索的关键字<input type="text" name="title" placeholder="关键字"></div>
        <input type="submit" value="搜索">
    </form>
    </h1>
</div>
{% endblock %}

movie/templates/movie/result.html
{% extends "movie_base.html" %}

{% block menu %}
<div class="history">
    <p><a href="{% url 'movie:history' %}">我的搜索历史</a></p>
</div>

{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'movie/css/home.css' %}">
<h3>总共搜索到{{ page_obj.paginator.count}}条记录</h3>
<h4><a href="{% url 'movie:home' %}">继续搜索</a></h4>
{% for movie in page_obj %}
{% if movie %}
<div style="border:1px solid green">
    <p>{{ movie.name }}</p>
    <p><a href={{ movie.href }}>{{ movie.href }}</a></p>
    <p>{{ movie.workers }}</p>
    <p>{{ movie.abstract }}</p>
    <p>{{ movie.score }}</p>
</div>
{% endif %}
{% endfor %}

        <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?title={{ params.title }}&num={{ params.num }}&page=1">&laquo; first</a>
                <a href="?title={{ params.title }}&num={{ params.num }}&page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?title={{ params.title }}&num={{ params.num }}&page={{ page_obj.next_page_number }}">next</a>
                <a href="?title={{ params.title }}&num={{ params.num }}&page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock %}

movie/templates/movie/search_history.html
{% extends "movie_base.html" %}

{% block content %}
<h3>总共查询出{{ historys.count }}条数据
</h3>
<table border="1" style="margin:auto;">
    <tr>
        <th>查询关键字</th>
        <th>查询数量</th>
        <th>查询时间</th>
        <th>查询结果</th>
    </tr>
    {% for history in historys %}
    <tr>
        <td>{{ history.title }}</td>
        <td>{{history.num}}</td>
        <td>{{ history.c_time}}</td>
        <td>{{history.result}}</td>
    </tr>
    {% endfor %}
</table>


{% endblock %}

movie/templates/movie/top250.html
{% extends "movie_base.html" %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'movie/css/home.css' %}">
<div class="" >
    {% for movie in page_obj %}
    <div class="movie_info">
        <p>{{ movie.rank }}</p>
        <p><a href={{ movie.href }}>{{ movie.href }}</a></p>
        <p>{{ movie.name }}</p>
        <p>{{ movie.worker }}</p>
    </div>
    <p>{% endfor %}</p>

        <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; 首页</a>
                <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">下一页</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">末页 &raquo;</a>
            {% endif %}
        </span>
    </div>
    {% endblock %}
</div>